/*
 * WIFI.h
 *
 *  Created on: 2023年1月25日
 *      Author: liguanxi
 */

#ifndef COMPONENTS_EXTERNAL_COMMUNICATION_WIFI_INCLUDE_WIFI_H_
#define COMPONENTS_EXTERNAL_COMMUNICATION_WIFI_INCLUDE_WIFI_H_



void wifi_init_sta(void);

#endif /* COMPONENTS_EXTERNAL_COMMUNICATION_WIFI_INCLUDE_WIFI_H_ */
